blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/your-username/mining-intelligence-system/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/your-username/mining-intelligence-system/wiki
    about: Check the documentation for usage guides and API reference